# Generated by Django 4.2.12 on 2024-05-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_created_at_alter_note_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='description',
        ),
    ]
