# Generated by Django 4.2.12 on 2024-05-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_text_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
